[[plugins]]
  package = "@netlify/plugin-gatsby"

[[plugins]]
  package = "/plugins/netlify-plugin-create-admin-user"

# [[plugins]]
#   package = "/plugins/netlify-plugin-process-notifications"

[build.processing.html]
  pretty_urls = false

[context.deploy-preview]
  publish = "public/"