name: Cypress e2e tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: site/gatsby-site
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "NPM Install"
        run: npm install --legacy-peer-deps

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          install: false
          config-file: cypress-config.js
        env:
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
