name: Cypress e2e tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Move to the site directory
        run: cd site/gatsby-site
      - name: "NPM Install"
        run: npm install
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          project: ./site/gatsby-site