name: WIP Public backup to the cloud

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 10 * * 1" # At 10:00 on Monday.
  workflow_dispatch:
    inputs:
      home:
        description: "This can be triggered from the GH page"
        required: false
        default: "This is not used"

defaults:
  run:
    shell: bash

jobs:
  build-and-run-backups:
    name: Backup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            coreutils \
            bash \
            tzdata \
            python3-pip \
            curl \
            npm

      - name: Generate public backup
        run: |
          /bin/backup.sh
        working-directory: db-backup
        env:
          IS_PUBLIC_BACKUP: true
          CLOUDFLARE_R2_ACCOUNT_ID: ${{ vars.CLOUDFLARE_R2_ACCOUNT_ID }}
          CLOUDFLARE_R2_WRITE_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_R2_WRITE_ACCESS_KEY_ID }}
          CLOUDFLARE_R2_WRITE_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_R2_WRITE_SECRET_ACCESS_KEY }}
          CLOUDFLARE_R2_BUCKET_NAME: ${{ vars.CLOUDFLARE_R2_BUCKET_NAME }}
          BACKUPFILE_PREFIX: backup
          MONGODB_URI: ${{ secrets.MONGODB_CONNECTION_STRING }}
          MONGODB_DBNAME: aiidprod
          MONGODB_DBNAME_TRANSLATIONS: translations
