name: Public backup to the cloud

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 10 * * 1" # At 10:00 on Monday.
  workflow_dispatch:
    inputs:
      home:
        description: 'This can be triggered from the GH page'
        required: false
        default: 'This is not used'

env:
  AWS_REGION: us-east-1                   # set this to your preferred AWS region, e.g. us-west-1

defaults:
  run:
    shell: bash

jobs:
  build-and-run-backups:
    name: Backup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
  
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker-db-backup/Dockerfile
          load: true
          tags: aiid-docker-backup:latest

      - name: Generate public backup
        run: |
          docker run --rm \
            -e IS_PUBLIC_BACKUP="true" \
            -e AWS_ACCESS_KEY_ID="${{ secrets.AWS_S3_BACKUP_USER_ACCESS_KEY_ID }}" \
            -e AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_S3_BACKUP_USER_SECRET_ACCESS_KEY }}" \
            -e TARGET_PRIVATE_BUCKET_URL="${{ vars.AWS_S3_PRIVATE_BUCKET }}" \
            -e TARGET_PUBLIC_BUCKET_URL="${{ vars.AWS_S3_PUBLIC_BUCKET }}" \
            -e CLOUDFLARE_R2_ACCOUNT_ID="${{ vars.CLOUDFLARE_R2_ACCOUNT_ID }}" \
            -e CLOUDFLARE_R2_WRITE_ACCESS_KEY_ID="${{ secrets.CLOUDFLARE_R2_WRITE_ACCESS_KEY_ID }}" \
            -e CLOUDFLARE_R2_WRITE_SECRET_ACCESS_KEY="${{ secrets.CLOUDFLARE_R2_WRITE_SECRET_ACCESS_KEY }}" \
            -e CLOUDFLARE_R2_BUCKET_NAME="${{ vars.CLOUDFLARE_R2_BUCKET_NAME }}" \
            -e BACKUPFILE_PREFIX="backup" \
            -e MONGODB_URI="${{ secrets.MONGODB_CONNECTION_STRING }}" \
            -e MONGODB_DBNAME="aiidprod" \
            -e MONGODB_DBNAME_TRANSLATIONS="translations" \
            -v ~:/mab \
            aiid-docker-backup:latest

