name: Process Notifications

on:
  workflow_call:
    inputs:
        environment:
          description: The Github environment to load secrets from
          type: string
          required: true

jobs:
  execute-mutation:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Call GraphQL API
        env:
          SITE_URL: ${{ vars.SITE_URL }}
          PROCESS_NOTIFICATIONS_SECRET: ${{ secrets.PROCESS_NOTIFICATIONS_SECRET }}
        run: |
          curl -X POST "$SITE_URL/api/graphql" \
          -H "Content-Type: application/json" \
          -H "PROCESS_NOTIFICATIONS_SECRET: $PROCESS_NOTIFICATIONS_SECRET" \
          -d '{"query":"mutation { processNotifications }"}'
