name: Deploy Production Branch

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 6,18 * * *"
  workflow_dispatch:

jobs:
  call-atlas:
    uses: ./.github/workflows/realm.yml
    secrets: inherit
    with:
      sha: ${{ github.sha }}
      environment: production
      runner-label: ${{ vars.PRODUCTION_RUNNER_LABEL }}

  call-test-build:
    uses: ./.github/workflows/test-build.yml
    secrets: inherit
    needs: call-atlas
    with:
      sha: ${{ github.sha }}
      environment: production
      netlify-context: production
      runner-label: ${{ vars.PRODUCTION_RUNNER_LABEL }}

  call-test:
    uses: ./.github/workflows/test.yml
    needs: call-test-build
    secrets: inherit
    with:
      sha: ${{ github.sha }}
      environment: production
      runner-label: ${{ vars.PRODUCTION_RUNNER_LABEL }}

  call-deploy:
    uses: ./.github/workflows/deploy.yml
    if: ${{ vars.FORCE_DEPLOY == 'true' }}
    needs: call-test
    secrets: inherit
    permissions:
      pull-requests: write
    with:
      environment: production
      sha: ${{ github.sha }}
      netlify-context: production
      netlify-alias:
      runner-label: ${{ vars.PRODUCTION_RUNNER_LABEL }}
