name: Realm Deploy

on:
  workflow_call:
    inputs:
      environment:
        description: The Github environment to load secrets from
        type: string
        required: true
      sha:
        description: The commit SHA to deploy
        type: string
        required: true

jobs:
  push:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha }}

      - name: "Install the Realm (Atlas) CLI"
        run: |
          npm install -g mongodb-realm-cli

      - name: Login
        run: |
          realm-cli login --api-key="${{ secrets.REALM_API_PUBLIC_KEY }}" --private-api-key="${{ secrets.REALM_API_PRIVATE_KEY }}" --realm-url https://realm.mongodb.com --atlas-url https://cloud.mongodb.com

      - name: Push
        run: |
          cd site/realm
          realm-cli push --remote="${{ vars.GATSBY_REALM_APP_ID }}" -y
