name: Deploy Staging Branch

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:

  call-atlas:
    uses: ./.github/workflows/realm.yml
    secrets: inherit
    with:
      sha: ${{ github.sha }}
      environment: staging
      runner-label: ${{ vars.STAGING_RUNNER_LABEL }}

  call-test-build:
    uses: ./.github/workflows/test-build.yml
    secrets: inherit
    needs: call-atlas
    with:
      sha: ${{ github.sha }}
      environment: staging
      netlify-context: production
      runner-label: ${{ vars.STAGING_RUNNER_LABEL }}

  call-test:
    uses: ./.github/workflows/test.yml
    needs: call-test-build
    secrets: inherit
    with:
      sha: ${{ github.sha }}
      environment: staging
      runner-label: ${{ vars.STAGING_RUNNER_LABEL }}

  call-deploy:
    uses: ./.github/workflows/deploy.yml
    if: ${{ vars.FORCE_DEPLOY == 'true' }}
    needs: call-test
    secrets: inherit
    permissions:
      pull-requests: write
    with:
      environment: staging
      sha: ${{ github.sha }}
      netlify-context: production
      netlify-alias: 
      runner-label: ${{ vars.STAGING_RUNNER_LABEL }}
